return {
  {
    "neo451/feed.nvim",
    cmd = "Feed",
    opts = {
      layout = { padding = { enabled = false } },
      feeds = {
        {
          "https://aws.amazon.com/blogs/infrastructure-and-automation/feed/",
          name = "AWS News - Infra",
          tags = { "aws", "infrastructure", "automation", "cloud" },
        },
        {
          "https://aws.amazon.com/blogs/architecture/feed/",
          name = "AWS News - Architecture",
          tags = { "aws", "architecture", "cloud" },
        },
        {
          "https://aws.amazon.com/blogs/aws/feed/",
          name = "AWS News",
          tags = { "aws", "announcements", "cloud" },
        },
        {
          "https://aws.amazon.com/blogs/database/feed/",
          name = "AWS News - Database",
          tags = { "aws", "database", "cloud", "data" },
        },
        {
          "https://aws.amazon.com/blogs/devops/feed/",
          name = "AWS News - DevOps",
          tags = { "aws", "devops", "cloud", "engineering" },
        },
        {
          "https://rss.beehiiv.com/feeds/ypr2bi0H9m.xml",
          name = "hungry minds",
          tags = { "software", "tech-news", "industry" },
        },
        {
          "https://thedecisionlab.com/feed/",
          name = "Decision Lab",
          tags = { "behavioral-science", "psychology", "research" },
        },
        {
          "https://coffeeandjunk.substack.com/feed",
          name = "Coffee and Junk",
          tags = { "software", "technology", "opinion", "tech-news" },
        },
        {
          "https://blog.pragmaticengineer.com/rss/",
          name = "The Pragmatic Engineer",
          tags = {
            "engineering",
            "career",
            "software-development",
            "management",
            "leadership",
          },
        },
        {
          "https://medium.com/feed/airtable-eng",
          name = "The Airtable Engineering Blog",
          tags = {
            "airtable",
            "engineering",
            "software-development",
            "product",
            "saas",
          },
        },
        {
          "https://medium.com/feed/medium-eng",
          name = "Medium Engineering",
          tags = { "medium", "engineering", "software-development", "platform" },
        },
        {
          "https://medium.com/feed/paypal-engineering",
          name = "The PayPal Technology Blog",
          tags = {
            "paypal",
            "engineering",
            "fintech",
            "payments",
            "software-development",
          },
        },
        {
          "https://medium.com/feed/pinterest-engineering",
          name = "Pinterest Engineering Blog",
          tags = {
            "pinterest",
            "engineering",
            "software-development",
            "data-science",
            "ai",
          },
        },
        {
          "http://engineering.grab.com/feed.xml",
          name = "Grab Tech",
          tags = {
            "grab",
            "engineering",
            "ride-hailing",
            "fintech",
            "logistics",
            "southeast-asia",
          },
        },
        {
          "https://slack.engineering/feed",
          name = "Slack Engineering",
          tags = {
            "slack",
            "engineering",
            "collaboration",
            "software-development",
            "messaging",
          },
        },
        {
          "http://githubengineering.com/atom.xml",
          name = "Engineering – The GitHub Blog",
          tags = {
            "github",
            "engineering",
            "devops",
            "tools",
            "version-control",
          },
        },
        {
          "https://developer.atlassian.com/blog/feed.xml",
          name = "Atlassian Developer Blog",
          tags = {
            "atlassian",
            "developer-tools",
            "engineering",
            "agile",
            "workflow",
          },
        },
        {
          "https://code.facebook.com/posts/rss",
          name = "Facebook Engineering",
          tags = {
            "meta",
            "facebook",
            "engineering",
            "research",
            "ai",
            "infrastructure",
          },
        },
        {
          "http://newsletter.grokking.org/?format=rss",
          name = "Grokking Newsletter",
          tags = {
            "software-development",
            "algorithms",
            "data-structures",
            "computer-science",
          },
        },
        {
          "http://www.ebaytechblog.com/feed/",
          name = "eBay Tech Blog",
          tags = { "ebay", "engineering", "ecommerce", "platform" },
        },
        {
          "https://engineering.atspotify.com",
          name = "Spotify Engineering",
          tags = {
            "spotify",
            "engineering",
            "streaming",
            "data",
            "music",
            "recommendation-systems",
          },
        },
        {
          "https://blog.twitter.com/engineering/en_us/blog.rss",
          name = "Twitter Engineering",
          tags = {
            "twitter",
            "engineering",
            "social-media",
            "scale",
            "realtime",
          },
        },
        {
          "https://stripe.com/blog/feed.rss",
          name = "Stripe Blog",
          tags = {
            "stripe",
            "fintech",
            "payments",
            "engineering",
            "api",
            "business",
          },
        },
        {
          "https://instagram-engineering.com/feed",
          name = "Instagram Engineering",
          tags = {
            "instagram",
            "meta",
            "engineering",
            "mobile",
            "social-media",
            "media",
          },
        },
        {
          "https://blog.cloudflare.com/rss/",
          name = "The Cloudflare Blog",
          tags = {
            "cloudflare",
            "cdn",
            "security",
            "networking",
            "performance",
            "web",
          },
        },
        {
          "https://blog.asana.com/category/eng/feed/",
          name = "Engineering – The Asana Blog",
          tags = {
            "asana",
            "engineering",
            "product-management",
            "collaboration",
            "saas",
          },
        },
        {
          "https://engineering.canva.com/rss",
          name = "Canva Engineering Blog",
          tags = {
            "canva",
            "engineering",
            "design-tools",
            "graphics",
            "web-development",
          },
        },
        {
          "https://medium.com/feed/airbnb-engineering",
          name = "The Airbnb Tech Blog",
          tags = {
            "airbnb",
            "engineering",
            "hospitality",
            "travel",
            "marketplace",
          },
        },
        {
          "https://dropbox.tech/feed",
          name = "Dropbox Tech",
          tags = {
            "dropbox",
            "engineering",
            "cloud-storage",
            "sync",
            "collaboration",
          },
        },
        {
          "https://wecode.wepay.com/feed.xml",
          name = "WePay Engineering Blog",
          tags = { "wepay", "fintech", "payments", "engineering" },
        },
        {
          "https://browser.engineering/rss.xml",
          name = "Web Browser Engineering",
          tags = {
            "browser",
            "web-development",
            "engineering",
            "computer-science",
            "systems",
          },
        },
        {
          "https://engineering.atspotify.com/feed/",
          name = "Spotify Engineering",
          tags = {
            "spotify",
            "engineering",
            "streaming",
            "data",
            "music",
            "recommendation-systems",
          },
        },
        {
          "https://engineering.fb.com/feed/",
          name = "Engineering at Meta",
          tags = {
            "meta",
            "facebook",
            "engineering",
            "infrastructure",
            "ai",
            "research",
          },
        },
        {
          "https://www.mindtheproduct.com/feed/",
          name = "Mind the Product",
          tags = {
            "product-management",
            "product-development",
            "ux",
            "strategy",
          },
        },
        {
          "https://jvns.ca/atom.xml",
          name = "Julia Evans",
          tags = {
            "personal-blog",
            "systems",
            "linux",
            "programming",
            "devops",
            "comics",
          },
        },
        {
          "https://feeds.feedburner.com/martinkl?format=xml",
          name = "Martin Kleppmann's blog",
          tags = {
            "personal-blog",
            "distributed-systems",
            "data-systems",
            "database",
            "research",
          },
        },
        {
          "https://overreacted.io/rss.xml",
          name = "Dan Abramov's Overreacted Blog",
          tags = {
            "personal-blog",
            "react",
            "frontend",
            "javascript",
            "web-development",
          },
        },
        {
          "https://danluu.com/atom.xml",
          name = "Dan Luu",
          tags = {
            "personal-blog",
            "performance",
            "systems",
            "hardware",
            "engineering-culture",
            "opinion",
          },
        },
        {
          "https://shopifyengineering.myshopify.com/blogs/engineering.atom",
          name = "Shopify Engineering",
          tags = { "shopify", "ecommerce", "engineering", "platform" },
        },
        {
          "https://engineering.grab.com/feed.xml",
          name = "Grab Tech",
          tags = {
            "grab",
            "engineering",
            "ride-hailing",
            "fintech",
            "logistics",
            "southeast-asia",
          },
        },
        {
          "https://joshwcomeau.com/rss.xml",
          name = "Josh Comeau's blog",
          tags = {
            "personal-blog",
            "frontend",
            "javascript",
            "react",
            "css",
            "web-development",
          },
        },
        {
          "https://www.uber.com/blog/engineering/rss/",
          name = "Uber Engineering Blog",
          tags = {
            "uber",
            "engineering",
            "ride-hailing",
            "logistics",
            "mobility",
            "ai",
          },
        },
        {
          "https://blog.singleton.io/index.xml",
          name = "Flurries of latent creativity - Stripe CTO blog",
          tags = {
            "stripe",
            "leadership",
            "cto",
            "engineering-management",
            "strategy",
            "opinion",
          },
        },
        {
          "https://sophiebits.com/atom.xml",
          name = "Sophie Alpert",
          tags = {
            "personal-blog",
            "react",
            "frontend",
            "javascript",
            "web-development",
          },
        },
        {
          "https://amasad.me/rss",
          name = "Amjad Masad",
          tags = {
            "personal-blog",
            "programming",
            "repl",
            "education",
            "coding",
            "software-development",
          },
        },
        {
          "https://signal.org/blog/rss.xml",
          name = "Signal Blog",
          tags = {
            "signal",
            "security",
            "privacy",
            "cryptography",
            "messaging",
          },
        },
        {
          "https://www.joelonsoftware.com/feed/",
          name = "Joel on Software",
          tags = {
            "software-development",
            "management",
            "career",
            "agile",
            "classic",
            "business",
          },
        },
      },
    },
  },
}
